all: outParta outPartb outPartc

outParta: Project2part1.c
	gcc -std=c99 -o outParta Project2part1.c -lm -D_POSIX_C_SOURCE=199309L

outPartb: Project2part1b.c
	gcc -std=c99 -o outPartb Project2part1b.c -lm -D_POSIX_C_SOURCE=199309L

outPartc: Project2part1c.c
	gcc -std=c99 -o outPartc Project2part1c.c -lm -D_POSIX_C_SOURCE=199309L

