all: outProb1 outProb3 outprob4

outProb1: problem1.c
		gcc -o -std=c99 outProb1 problem1.c -lm -pthread

outProb3: problem3.c
		gcc -o -std=c99 outProb3 problem3.c -lm -pthread

outProb4: problem4.c
		gcc -o -std=c99 outProb4 problem4.c -lm -pthread
