all: outProb1 outProb3 outProb4

outProb1: problem1.c
		gcc -std=c99 -o outProb1 problem1.c -lm -pthread

outProb3: problem3.c
		gcc -std=c99 -o outProb3 problem3.c -lm -pthread

outProb4: problem4.c
		gcc -std=c99 -o outProb4 problem4.c -lm -pthread
